controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint1
      - Joint2
      - Joint3
initial:  # Define initial robot poses per group
  - group: arm
    pose: init_pose